<?php

/**
 * @file
 * Code for the Stanford SOE Helper module.
 */


/**
 * Implements hook_help().
 */
function stanford_soe_helper_help($path, $arg) {

  if ($path == 'admin/help#stanford_soe_helper') {
    $output = '<h3>' . t('About the Stanford SoE Helper') . '</h3>';
    $output .= '<p>' . t('The Stanford SoE Helper module provides settings specific for the SoE site.') . '</p>';
    $output .= l(t("See README.md"), drupal_get_path('module', 'stanford_soe_helper') . '/README.md');
    return $output;
  }
}

/**
 * Implements hook_init().
 */
function stanford_soe_helper_init() {

  // Add css files
  $file_paths = array(
    drupal_get_path('module', 'stanford_soe_helper') . "/css/soe_helper.css",
    drupal_get_path('module', 'stanford_soe_helper') . "/css/stanford_news_layouts.css"
  );

  // CSS Injector file weights start at 200.
  // See http://www.rit.edu/drupal/api/drupal/sites!all!modules!css_injector!css_injector.module/7.43.
  $weight = 190;
  $conditions = "admin
admin*
admin/*
block/*/edit*
block/add*
block/*/delete
node/*/edit
node/add*
node/*/delete
user/*/edit";

  $css_rules = array();
  $css_rules['rule_conditions'] = $conditions;
  $css_rules['rule_type'] = CSS_INJECTOR_PAGES_NOTLISTED;

  $pass = _css_injector_evaluate_rule($css_rules);
  if ($pass) {
    foreach ($file_paths as $file_path) {

      drupal_add_css($file_path, array(
        'type' => 'file',
        'group' => CSS_THEME,
        'media' => "all",
        'preprocess' => TRUE,
        'weight' => $weight
      ));
      $weight = $weight++;
    }
  }
}

