<?php
/**
 * @file
 * Code for the stanford_soe_helper_homepage feature.
 */

include_once 'stanford_soe_helper_homepage.features.inc';

/**
 * Implementation of hook_init().
 */
function stanford_soe_helper_homepage_init() {

  $context_status = variable_get('context_status', array());
  $context_status['stanford_jumpstart_soe_home'] = FALSE;
  $context_status['stanford_jumpstart_home_terman'] = TRUE;
  variable_set('context_status', $context_status);

  $cbc_layouts = variable_get('contextual_block_class', array());
  $cbc_layouts['stanford_jumpstart_soe_home']['views-stanford_events_views-block'][] = 'span4 well';
  $cbc_layouts['stanford_jumpstart_soe_home']['bean-homepage-about-block'][] = 'span4 well';
  $cbc_layouts['stanford_jumpstart_soe_home']['views-9bf4ec9695a5b13242ba5a4898a6b635'][] = 'span4 well';
  $cbc_layouts['stanford_jumpstart_soe_home']['bean-jumpstart-large-custom-block'][] = 'span8 well';
  $cbc_layouts['stanford_jumpstart_soe_home']['bean-jumpstart-small-custom-block'][] = 'span4 well';
  variable_set('contextual_block_class', $cbc_layouts);

}

/*  public function execute(&$args = array()) {

    // Install default JSE block classes.
    $fields = array('module', 'delta', 'css_class');
    $values = array(
      array("bean", "jumpstart-small-custom-block", "well"),
      array("bean", "jumpstart-large-custom-block", "well"),
    );
    // Key all the values.
    $insert = db_insert('block_class')->fields($fields);
    foreach ($values as $value) {
      $db_values = array_combine($fields, $value);
      $insert->values($db_values);
    }
    $insert->execute();
  }

}
*/