<?php
/**
 * @file
 * Code for the stanford_soe_helper_homepage feature.
 */

include_once 'stanford_soe_helper_homepage.features.inc';


/**
 * Implementation of hook_init().
 */
function stanford_soe_helper_homepage_init() {

  $context_status = variable_get('context_status', array());
  $context_status['stanford_jumpstart_soe_home'] = FALSE;
  $context_status['stanford_jumpstart_home_terman'] = TRUE;
  variable_set('context_status', $context_status);

  $cbc_layouts = array();
  $cbc_layouts['stanford_jumpstart_soe_home']['views-9bf4ec9695a5b13242ba5a4898a6b635'][] = 'span4 well';
  variable_set('contextual_block_class', $cbc_layouts);

}
