<?php

/**
 * @file
 * Code for the Stanford SoE Helper Landing Page feature.
 */

include_once 'stanford_soe_helper_landing_page.features.inc';

/**
 * Add the accent color field to Stanford Page
 *
 * If the soe_accent_color vocabulary exists, then add the
 * field to the Stanford Page. We're doing it this way because
 * the soe_accent_color vocabulary is defined in a separate module.
 */
function _stanford_soe_helper_landing_page_add_color_field() {

  module_load_include('module', 'stanford_soe_helper_sitewide');
  stanford_soe_helper_sitewide_add_tax_field(
    'field_s_title_accent_color',
    'soe_accent_color',
    'field_landing_page_item',
    'field_collection_item',
    'Title accent color');

 stanford_soe_helper_sitewide_add_tax_field(
    'field_s_image_accent_color',
    'soe_accent_color',
    'field_landing_page_item',
    'field_collection_item',
    'Image accent color');
}
