<?php

/**
 * @file
 * Code for the Stanford SoE Helper Landing Page feature.
 */

include_once 'stanford_soe_helper_landing_page.features.inc';

function stanford_soe_helper_landing_page_preprocess(&$variables, $hook) {
  _stanford_soe_helper_landing_page_add_color_field();
}
/**
 * Add the accent color field to Stanford Page
 *
 * If the soe_accent_color vocabulary exists, then add the
 * field to the Stanford Page. We're doing it this way because
 * the soe_accent_color vocabulary is defined in a separate module.
 */
function _stanford_soe_helper_landing_page_add_color_field() {

  module_load_include('module', 'stanford_soe_helper_sitewide');

  // Add the color field to the field collection

  $fc_fields = field_info_instances('field_collection_item', 'field_landing_page_item');
  dpm($fc_fields);
  if (!array_key_exists('field_s_name_accent_color')) {

    // Create the color field.

    $field = stanford_soe_helper_sitewide_add_tax_field(
      'field_s_name_accent_color',
      'soe_accent_color',
      NULL,
      'Name accent color');

   $fc_fields[] = $field;

   // save it here!

  }

  /*
   * In stanford_soe_helper_landing_page:
   *
Get the field - $fc_fields = field_info_instances('field_collection_item', 'field_landing_page_item');
Check to see if field is already in use.
Create field
Add field (array_push()) and push the field onto the instance.
Use hook_preprocess() for testing and move to install()

Deleting the field:
Find field as above
use field_delete_field() to remove.
   */
}
