<?php
/**
 * @file
 * stanford_soe_helper_landing_page.install
 */

/**
 * Implements hook_install().
 */
function stanford_soe_helper_landing_page_install() {
  _stanford_soe_helper_landing_page_add_color_field();

  $schema_version = drupal_get_installed_schema_version('stanford_soe_helper_landing_page');
  if ($schema_version < 7101) {
    drupal_set_installed_schema_version('stanford_soe_helper_landing_page', 7101);
  }
}


/**
 * Implements hook_enable().
 */
function stanford_soe_helper_landing_page_enable() {
  /*
   *mymodule_cache_rebuild();
   */
  /* Your code here */
}

/**
 * Implements hook_disable().
 */
function stanford_soe_helper_landing_page_disable() {
  /*
   *mymodule_cache_rebuild();
   */
  /* Your code here */
}

/**
 * Implements hook_uninstall().
 */
function stanford_soe_helper_landing_page_uninstall() {
  field_delete_instance('field_s_name_accent_color');
}

/**
 * Implements hook_update_N().
 */
function stanford_soe_helper_landing_page_update_7101() {
  _stanford_soe_helper_landing_page_add_color_field();
}

/**
 * Add the accent color field to Stanford Page
 *
 * If the soe_accent_color vocabulary exists, then add the
 * field to the Stanford Page. We're doing it this way because
 * the soe_accent_color vocabulary is defined in a separate module.
 */
function _stanford_soe_helper_landing_page_add_color_field() {

  module_load_include('module', 'stanford_soe_helper_sitewide');
  stanford_soe_helper_sitewide_add_tax_field(
    'field_s_name_accent_color',
    'soe_accent_color',
    'field_landing_page_item',
    'Name accent color');
}

