<?php
/**
 * @file
 * Code for the Stanford SOE Helper Bean Types module.
 */

/**
 * Implements hook_preprocess_entity().
 */
function stanford_soe_helper_bean_types_preprocess_entity(&$vars) {
  if ($vars['entity_type'] == 'bean' && $vars['elements']['#bundle'] == 'stanford_postcard_linked') {
    if (isset($vars['elements']['#entity']->field_s_postcard_linked_color[LANGUAGE_NONE][0]['tid'])) {
      $tid = $vars['elements']['#entity']->field_s_postcard_linked_color[LANGUAGE_NONE][0]['tid'];
      $term = taxonomy_term_load($tid);
      $vars['classes_array'][] = 'postcard-linked-arrow-color-' . drupal_clean_css_identifier($term->name);
    }
  }
}
