<?php
/**
 * @file
 * Code for Stanford SoE Helper Magazine Views module.
 *
 * Custom views for magazine. These are views that are not features.
 */

/**
 * Implements hook_views_api().
 *
 * Enabling using templates inside module
 */
function stanford_soe_helper_mag_views_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'stanford_soe_helper_mag_views'),
    'template path' => drupal_get_path('module', 'stanford_soe_helper_mag_views') . '/templates',
  );
}

/**
 * Get the featured article ready to print
 *
 * @param $row
 * @return array
 */
function _stanford_mag_issue_get_feat_art($row) {
  $vars = array(
    'image' => '',
    'date' => '',
    'color' => '',
    'title' => '',
    'dek' => '',
    'topics' => '',
    'edit-link'=> '',
    'nid' => '',
  );

  if (isset($row->node_field_data_field_s_mag_issue_featured_nid)) {
    $vars['nid'] = $row->node_field_data_field_s_mag_issue_featured_nid;

    if (isset($row->field_field_s_mag_article_image[0]['rendered'])) {
      $vars['image'] = drupal_render($row->field_field_s_mag_article_image[0]['rendered']);
    }
    if (isset($row->field_field_s_mag_article_date[0]['rendered'])){
      $vars['date'] = drupal_render($row->field_field_s_mag_article_date[0]['rendered']);
    }
    if (isset($row->field_field_s_mag_article_accent_color[0]['rendered'])) {
      $vars['color'] = drupal_render($row->field_field_s_mag_article_accent_color[0]['rendered']);
    }
    if (isset($row->node_field_data_field_s_mag_issue_featured_title)) {
      $vars['title'] = $row->node_field_data_field_s_mag_issue_featured_title;
    }
    if (isset($row->field_field_s_mag_article_dek[0]['rendered'])) {
      $vars['dek'] = drupal_render($row->field_field_s_mag_article_dek[0]['rendered']);
    }
    $vars['topics'] = _stanford_mag_issue_get_topics($row->field_field_s_mag_article_topics);
    $vars['edit-link'] = _stanford_mag_issue_get_edit_link($row->node_field_data_field_s_mag_issue_featured_nid);
  }

  return $vars;
}

/**
 * Get the second article ready to print
 *
 * @param $row
 * @return array
 */
function _stanford_mag_issue_get_art_2($row) {
  $vars = array(
    'image' => '',
    'date' => '',
    'color' => '',
    'title' => '',
    'dek' => '',
    'topics' => '',
    'edit-link'=> '',
    'nid' => '',
  );

  if (isset($row->node_field_data_field_s_mag_issue_article_2_nid))
  {
    $vars['nid'] = $row->node_field_data_field_s_mag_issue_article_2_nid;
    $vars['topics'] = _stanford_mag_issue_get_topics($row->field_field_s_mag_article_topics_1);
    $vars['edit-link'] = _stanford_mag_issue_get_edit_link($row->node_field_data_field_s_mag_issue_article_2_nid);
    if (isset($row->field_field_s_mag_article_image_1[0]['rendered'])) {
      $vars['image'] = drupal_render($row->field_field_s_mag_article_image_1[0]['rendered']);
    }
    if (isset($row->field_field_s_mag_article_date_1[0]['rendered'])) {
      $vars['date'] = drupal_render($row->field_field_s_mag_article_date_1[0]['rendered']);
    }
    if (isset($row->field_field_s_mag_article_accent_color_1[0]['rendered'])) {
      $vars['color'] = drupal_render($row->field_field_s_mag_article_accent_color_1[0]['rendered']);
    }
    if (isset($row->node_field_data_field_s_mag_issue_article_2_title)) {
      $vars['title'] = $row->node_field_data_field_s_mag_issue_article_2_title;
    }
  }

  return $vars;
}

/**
 * Get the third article ready to print
 *
 * @param $row
 * @return array
 */
function _stanford_mag_issue_get_art_3($row) {
  $vars = array(
    'image' => '',
    'date' => '',
    'color' => '',
    'title' => '',
    'dek' => '',
    'topics' => '',
    'edit-link'=> '',
    'nid' => '',
  );

  if (isset($row->node_field_data_field_s_mag_issue_article_3_nid)) {
    $vars['nid'] = $row->node_field_data_field_s_mag_issue_article_3_nid;
    $vars['topics'] = _stanford_mag_issue_get_topics($row->field_field_s_mag_article_topics_2);
    $vars['edit-link'] = _stanford_mag_issue_get_edit_link($row->node_field_data_field_s_mag_issue_article_3_nid);
    $vars['title'] = $row->node_field_data_field_s_mag_issue_article_3_title;
    if (isset($row->field_field_s_mag_article_image_2[0]['rendered'])) {
      $vars['image'] = drupal_render($row->field_field_s_mag_article_image_2[0]['rendered']);
    }
    if (isset($row->field_field_s_mag_article_date_2[0]['rendered'])) {
      $vars['date'] = drupal_render($row->field_field_s_mag_article_date_2[0]['rendered']);
    }
    if (isset($row->field_field_s_mag_article_accent_color_2[0]['rendered'])) {
      $vars['color'] = drupal_render($row->field_field_s_mag_article_accent_color_2[0]['rendered']);
    }
  }
  return $vars;
}

/**
 * Get the fourth article ready to print
 *
 * @param $row
 * @return array
 */
function _stanford_mag_issue_get_art_4($row) {
  $vars = array(
    'image' => '',
    'date' => '',
    'color' => '',
    'title' => '',
    'dek' => '',
    'topics' => '',
    'edit-link'=> '',
    'nid' => '',
  );
  if (isset($row->node_field_data_field_s_mag_issue_article_4_nid)) {
    $vars['nid'] =  $row->node_field_data_field_s_mag_issue_article_4_nid;
    $vars['nid'] = $row->node_field_data_field_s_mag_issue_article_4_nid;
    $vars['title'] = $row->node_field_data_field_s_mag_issue_article_4_title;
    $vars['topics'] = _stanford_mag_issue_get_topics($row->field_field_s_mag_article_topics_3);
    $vars['edit-link'] = _stanford_mag_issue_get_edit_link($row->node_field_data_field_s_mag_issue_article_4_nid);
    if (isset($row->field_field_s_mag_article_image_3[0]['rendered'])) {
      $vars['image'] = drupal_render($row->field_field_s_mag_article_image_3[0]['rendered']);
    }
    if (isset($row->field_field_s_mag_article_date_3[0]['rendered'])) {
      $vars['date'] = drupal_render($row->field_field_s_mag_article_date_3[0]['rendered']);
    }
    if (isset($row->field_field_s_mag_article_accent_color_3[0]['rendered'])) {
      $vars['color'] = drupal_render($row->field_field_s_mag_article_accent_color_3[0]['rendered']);
    }

  }
  return $vars;
}


/**
 * Get the fifth article ready to print
 *
 * @param $row
 * @return array
 */
function _stanford_mag_issue_get_art_5($row) {
  $vars = array(
    'image' => '',
    'date' => '',
    'color' => '',
    'title' => '',
    'dek' => '',
    'topics' => '',
    'edit-link'=> '',
    'nid' => '',
  );
  if (isset($row->node_field_data_field_s_mag_issue_article_5_nid)) {
    $vars['title'] = $row->node_field_data_field_s_mag_issue_article_5_title;
    $vars['topics'] =_stanford_mag_issue_get_topics($row->field_field_s_mag_article_topics_4);
    $vars['edit-link'] = _stanford_mag_issue_get_edit_link($row->node_field_data_field_s_mag_issue_article_4_nid);
    $vars['nid'] = $row->node_field_data_field_s_mag_issue_article_5_nid;
    if (isset($row->field_field_s_mag_article_image_4[0]['rendered'])) {
      $vars['image'] = drupal_render($row->field_field_s_mag_article_image_4[0]['rendered']);
    }
    if (isset($row->field_field_s_mag_article_date_4[0]['rendered'])) {
      $vars['date'] = drupal_render($row->field_field_s_mag_article_date_4[0]['rendered']);
    }
    if (isset($row->field_field_s_mag_article_accent_color_4[0]['rendered'])) {
      $vars['color'] = drupal_render($row->field_field_s_mag_article_accent_color_4[0]['rendered']);
    }
  }
  return $vars;
}

/**
 * Print the featured article
 *
 * @param $vars
 * @return string
 */
function _stanford_mag_issue_print_feat_art($vars) {

  $output = '';

  if ($vars['nid'] != '') {
    $output .= '<div class="mag-feat-article-container">';
    $output .= '  <div class="mag-article-img">' . $vars['image'] . '</div>';
    $output .= '  <div class ="mag-article-content-container">';
    $output .= '    <div class="mag-article-date">' . $vars['date'] . '</div>';
    $output .= '    <div class="mag-article-title mag-article-color-' . $vars['color'] . '">'
      . l(t($vars['title']), "node/" . $vars['nid']) . '</div>';
    $output .= '    <div class="mag-article-dek">' . $vars['dek'] . '</div>';
    $output .= '    <div class="mag-article-topics">' . $vars['topics'] . '</div>';
    $output .= $vars['edit-link'];
    $output .= '  </div>';
    $output .= '</div>';
  }

  return $output;
}

/**
 * Print an article
 *
 * @param $vars
 * @return string
 */
function _stanford_mag_issue_print_art($vars) {

  $output = '';

  if ($vars['nid'] != '') {
    $output .= '<div class="mag-article-container">';
    $output .= '<div class="mag-article-img">' . $vars['image'] . '</div>';
    $output .= '  <div class ="mag-article-content-container">';
    $output .= '    <div class="mag-article-date">' . $vars['date'] . '</div>';
    $output .= '    <div class="mag-article-title mag-article-color-' . $vars['color'] . '">'
      . l(t($vars['title']), "node/" . $vars['nid']) . '</div>';
    $output .= '    <div class="mag-article-topics">' . $vars['topics'] . '</div>';
    $output .= $vars['edit-link'];
    $output .= '  </div>';
    $output .= '</div>';
  }

  return $output;
}

/**
 * Get the topics ready to print
 *
 * @param $topic_list
 * @return string
 */
function _stanford_mag_issue_get_topics($topic_list) {
  $topics = '';
  if (is_array($topic_list)) {
    foreach ($topic_list as $t => $topic) {
      if ($t > 0) {
        $topics .= ', ';
      }
      $topics .= drupal_render($topic['rendered']);
    }
  }
  return $topics;
}

/**
 * Return the access privileges for the current user and this node
 *
 * @param $nid
 * @return bool
 */
function _stanford_mag_issue_have_access($nid) {
  global $user;
  $have_access = &drupal_static(__FUNCTION__);
  if (!isset($have_access)) {
    $have_access = FALSE;
    $node = node_load($nid);
    if (node_access("update", $node, $user) === TRUE) {
      $have_access = TRUE;
    }
  }
  return $have_access;
}

/**
 * Return an edit link for this node
 *
 * @param $nid
 * @return string
 */
function _stanford_mag_issue_get_edit_link($nid) {
  $node_path = drupal_lookup_path('alias','node/'.$nid);
  if (_stanford_mag_issue_have_access($nid)) {
    return '<div class="edit-link">' . l(t("Edit"), "node/" . $nid . '/edit', array("query" => array("destination" => $node_path))) . '</div>';
  }
  return '';
}
