<?php
/**
 * @file
 * Code for the Stanford SoE Magazine feature.
 */

include_once 'stanford_soe_helper_magazine.features.inc';

/**
 * Implements hook_menu_block_blocks().
 */

function stanford_soe_helper_magazine_menu_block_blocks() {
  // The array key is the block delta used by menu block.
  return array(
    'stanford_soe_helper_mag-1' => array(
      'menu_name' => 'menu-magazine',
      'parent_mlid' => 0,
      'title_link' => 0,
      'admin_title' => 'Digital Magazine Menu - Primary - 2 Depths',
      'level' => 1,
      'follow' => 0,
      'depth' => 2,
      'expanded' => 0,
      'sort' => 0,
    ),
  );
}


